name: Other
description: Use this issue for any questions/suggestions or closed internships.
title: "Issue: "
labels: ["other"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to create this issue!